title: SWATHY P THANKACHAN
logo: /img/photo.jpg
#theme: jeykll-theme-minimal
#remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag



